from app.models.resume import Resume, ResumeSection
from app.models.student import (
    EmbeddingIndex,
    ExtractLog,
    ResumeReviewVersion,
    Student,
    StudentAward,
    StudentBasicInfo,
    StudentCompetition,
    StudentEducation,
    StudentFacultyMatch,
    StudentInternship,
    StudentJobMatch,
    StudentPaper,
    StudentPatent,
    StudentPortrait,
    StudentProject,
    StudentResumeChunk,
    StudentSkill,
)

all_models = [
    Resume,
    ResumeSection,
    Student,
    StudentBasicInfo,
    StudentEducation,
    StudentInternship,
    StudentProject,
    StudentAward,
    StudentPaper,
    StudentPatent,
    StudentCompetition,
    StudentSkill,
    StudentResumeChunk,
    StudentPortrait,
    ResumeReviewVersion,
    ExtractLog,
    EmbeddingIndex,
    StudentFacultyMatch,
    StudentJobMatch,
]
